### ISSUE TITLE
Unknown UART output.

### ISSUE THREAD

**Issue by sheinz** [espressif/ESP8266_MESH_DEMO#10]
I tried the Mesh Demo with several ESP-12E modules. 
The demo seems to work but I don't see the logging on the UART from the devices.
It seems like the wrong baud rate but I tried them all and don't see anything readable.

Is there some trick to get output on the port visible?
Thanks in advance.
Great job, btw.

**Comment by AlenXiao** [comment]
Hi,

The current baut rate is 74880.

You can use API(uart_div_modify) to set baut rate for serial port.

Thanks.
Alen Xiao.

在 2016-4-4 6:15, sheinz 写道:
>
> I tried the Mesh Demo with several ESP-12E modules.
> The demo seems to work but I don't see the logging on the UART from 
> the devices.
> It seems like the wrong baud rate but I tried them all and don't see 
> anything readable.
>
> Is there some trick to get output on the port visible?
> Thanks in advance.
> Great job, btw.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/espressif/ESP8266_MESH_DEMO/issues/10>
>

-- 

Best regards,
Alen Xiao     肖月振
Espressif Systems

www.espressif.com
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by sheinz** [comment]
Hi Alen,

Setting  UART speed with:
`uart_div_modify(0, UART_CLK_FREQ / 115200);`
helped.

I also noticed that SDK that is used in MESH_DEMO is different than officially release v1.5.2.
It seems like used SDK is ahead of the MESH API that is officially released.
Are those changes in MESH API going to be released within the official SDK?

Thanks for the help,
Yuriy.

**Comment by AlenXiao** [comment]
Hi, Yuriy,

The SDK used by mesh is sdk-v1.5.1.
Please use the API released officially.

We will merge current mesh and sdk-v1.5.2 soon.

Thanks.
Alen Xiao.


在 2016-4-5 19:07, sheinz 写道:
>
> Hi Alen,
>
> Setting UART speed with:
> |uart_div_modify(0, UART_CLK_FREQ / 115200);|
> helped.
>
> I also noticed that SDK that is used in MESH_DEMO is different than 
> officially release v1.5.2.
> It seems like used SDK is ahead of the MESH API that is officially 
> released.
> Are those changes in MESH API going to be released within the official 
> SDK?
>
> Thanks for the help,
> Yuriy.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/espressif/ESP8266_MESH_DEMO/issues/10#issuecomment-205757556>
>

-- 

Best regards,
Alen Xiao     肖月振
Espressif Systems

www.espressif.com
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China
