### ISSUE TITLE
Send data from all node using UART to server + α

### ISSUE THREAD

**Issue by yamipro** [espressif/ESP8266_MESH_DEMO#22]
I have complete the mesh network and i can ping the root node but cant ping any of non-root node.
all node start DHCP server and gw with 192.168.x.1 but why all of the non-root node connect to other node using IP 2.255.255.x?

i want to make a monitoring system that will push the data through UART and send it to server. how to make the esp read the serial and forward the data thru all node to the server?

**Comment by AlenXiao** [comment]
You can't ping any non-root device, but you can access every non-root device through root using packet with format of mesh.

please use os_printf to print debug information to serial port.

You just need to build packet with format of mesh to server, the packet will been forwarded to server.
