### ISSUE TITLE
Solution and a crash on root node

### ISSUE THREAD

**Issue by bcatalin** [espressif/ESP8266_MESH_DEMO#7]
Ok so from documentation I can see that I can go only 5 levels down. But what is the solution if I want to make a line of 20 ESPs with a leaf at one end and the root ( connected to a wifi router) on the other end ?

**Comment by bcatalin** [comment]
I have a crash on root node with your demo code:

My mesh network is made with 3 nodes, one root and 2 leafs.


cidx:1, count:1 mac_list:
idx:0, 18:fe:34:d2:34:f7
free heap:41912
[mesh_demo.c:169-esp_mesh_demo_test] Entering...
[mesh_demo.c:170-esp_mesh_demo_test] Root:1

cidx:1, count:1 mac_list:
idx:0, 18:fe:34:d2:34:f7
free heap:41912
idx: 0, mac:e8:bd:d1:bc:b6:c0
idx: 1, mac:5c:cf:7f:81:c9:96
idx: 2, mac:18:fe:34:d2:34:f7
not as root, grp_id:18:fe:34:00:00:50 mac:18:fe:34:d2:32:ed root:18:fe:34:d2:34:f7
state: 5 -> 0 (0)
rm 0
f r0, station: 5c:cf:7f:81:c9:96 leave, AID = 1
rm 1
station: 18:fe:34:d2:34:f7 leave, AID = 2
rm 2
espconn_mesh_ap_server_discon_cb, RIP: 2.255.255.2RP = 48574
Fatal exception 28(LoadProhibitedCause):
epc1=0x4000dfa4, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
stack sp is 3ffffe10
*** stack dump start ***
PC = 0x4000dfa4
3ffffe10: 00000004 40100d26 0000001a 00000002
3ffffe20: 3fff17f0 00000000 00000000 402726eb
3ffffe30: 3fff0da0 00000000 3ffffe96 00000000
3ffffe40: 00000000 00000004 3fff17f0 00000001
3ffffe50: 00000001 40272928 3fff0da0 00000000
3ffffe60: 00000001 00000000 00000000 00000000
3ffffe70: 00000001 0000000a 00000000 00000000
3ffffe80: 00000000 00000000 00000000 00000000
3ffffe90: 00000010 00000d26 3ffef62c 3fff0d88
3ffffea0: 00000001 00000001 00000004 3fff0d8c
3ffffeb0: 00000000 00000004 00000000 00000000
3ffffec0: 0000000a 3ffef804 3ffef804 4026dbfc
3ffffed0: 3ffef62c 00000000 3ffef648 40276210
3ffffee0: 3fff0d92 00000000 00000000 3ffea834
3ffffef0: 00000000 00000000 00000000 00000000
3fffff00: 00000000 00000000 00000000 00000000
3fffff10: d234fe18 3ffeed32 3fff0850 4027a501
3fffff20: 3fff0d88 402719db 00000000 3fff1308
3fffff30: 3fff1308 40271a5d 00000000 000000ff
3fffff40: 00000000 40271ad0 3ffef648 3fff1610
3fffff50: 0000bdbe 00000001 000000e3 00000000
3fffff60: 40260898 3ffef150 3ffef150 3fffdc60
3fffff70: 402608cc 3fffdab0 00000000 3fffdc60
3fffff80: 3ffef1b0 3fff1628 3fff13f0 3fffdcc0
3fffff90: 3ffef648 3ffea010 00000001 00000000
3fffffa0: 3fff1610 40000f49 ffffff01 ffffffff
3fffffb0: 40000e19 40001878 00000002 00000000
3fffffc0: 00000000 ffffffff ffffffff 40100270
3fffffd0: 40100276 00000002 00000000 00009150
3fffffe0: 4010000d 00000bb0 00000004 e6117827
3ffffff0: 4000044c 00000000 00000000 d9ac0844
*** stack dump end ***

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 31976, room 16 
tail 8
chksum 0xa7
load 0x3ffe8000, len 2196, room 0 
tail 4
chksum 0xb3
load 0x3ffe88a0, len 2992, room 4 
tail 12
chksum 0x81
csum 0x81
don't use rtc mem data
rdSmesh version: v1.0.0
mode : sta(18:fe:34:d2:32:ed) + softAP(1a:fe:34:d2:32:ed)
add if0
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100

**Comment by AlenXiao** [comment]
Sorry, the max-hop supported by esp-mesh is 5 (because of free heap size).

we have updated the code, please pull the current code, and we will test your case.

**Comment by bcatalin** [comment]
The crash is with latest version. I don't see any modification from yesterday. Did you updated the code or not? Thanks

**Comment by AlenXiao** [comment]
i will fix the problem reported by you as soon as possible.

**Comment by AlenXiao** [comment]
Hi, bcatalin,

I have fixed the crash you reported, and I shall push the current lib to github tomorrow.

**Comment by AlenXiao** [comment]
We have fixed the crash, please pull the current lib.

**Comment by bcatalin** [comment]
Excellent. I will test it.
